"""Add authentication fields to students

Revision ID: 8eeab94093b2
Revises: ab3ce4377182
Create Date: 2025-11-16 21:24:29.891503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eeab94093b2'
down_revision = 'ab3ce4377182'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('students', sa.Column('email', sa.String(), nullable=True))
    op.add_column('students', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('students', sa.Column('name', sa.String(), nullable=True))
    
    # Set default values for existing students (they were auto-created for testing)
    # Use student_id as email prefix to make them unique but invalid for login
    op.execute("""
        UPDATE students 
        SET email = student_id || '@temp.invalid',
            password_hash = '$2b$12$INVALIDHASHFOREXISTINGSTUDENTS',
            name = 'Temp Student'
        WHERE email IS NULL
    """)
    
    # Now make columns NOT NULL
    op.alter_column('students', 'email', nullable=False)
    op.alter_column('students', 'password_hash', nullable=False)
    
    # Create unique index on email
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_column('students', 'name')
    op.drop_column('students', 'password_hash')
    op.drop_column('students', 'email')
    # ### end Alembic commands ###




